version: 2.1

workflow:
  test-deploy:
    jobs:
      - test

jobs:
  build:
    docker:
      - image: cimg/python:3.11.0
    steps:
      - checkout
      - run: python --version
      - run:
          name: Install updates
          command: apt-get update
      - run:
          name: Run some hello
          command: python hello.py
